name: Build Docker
run-name: Build Docker
on: [push]

jobs:
  Build Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check files 
        run: |
          for file in *.html; do
            if grep -q "$file" "$file"; then
              echo "File $file contains canonical tag with .html!"
              exit 1
            else
              echo "File $file is correct!"
            fi
          done
      - name: Build Docker image
        run : |
          apt-get install ca-certificates curl gnupg
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          apt-get install docker-ce-cli
          echo "${{ secrets.DOCKERGIT_TOKEN }}" | docker login git.woodburn.au -u nathanwoodburn --password-stdin
          docker build -t woodburn-website:latest .
          docker push git.woodburn.au/nathanwoodburn/woodburn-website:latest


