name: Check Code Quality
run-name: Ruff CI
on:
  push:

jobs:
  RuffCheck:
    runs-on: [ubuntu-latest, amd]
    steps:
      - uses: actions/checkout@v2
      - name: Run Ruff Check
        uses: astral-sh/ruff-action@v4.1.0  
